### ISSUE TITLE
Gather information and news articles from news websites

### ISSUE THREAD

**Issue by arch-dimension** [ICST-Technion/TechnioNLPScrapper#10]
## Value Statement:
As a Sikkuy-Aufoq manager, I want to be able to gather information from news articles from websites such as Ynet and The marker
(optionally social media such as Twitter and Facebook) so that we can learn about the general sentiment regarding the Arab community 

related to #7 

## Acceptance Criteria
* The ability to gather information from Hebrew news websites
*  optionally: The ability to gather information from social media

## Development Complete
 The code is complete.
 Functionality is working.
 Any required downstream Docker file changes are made.
## Tests Automated
 Unit/function tests have been automated and incorporated into the build.
 100% automated unit/function test coverage for new or changed APIs.

**Comment by jouwana** [comment]
there is an API that can search google and give us back URLs that we can use in a webscrapper.
we could probably use our keywords and constraints (even website constraints, not sure about illegal keywords, need to check advanced google search options) which would make the gathering part easier, as we would just need to use the URLs in the scrapper.
