### ISSUE TITLE
Build the UI as designed

### ISSUE THREAD

**Issue by arch-dimension** [ICST-Technion/TechnioNLPScrapper#14]
## Value Statement:
The UI is the way the client interacts with our project, finishing it earlier will allow us to black box test earlier.

## Acceptance Criteria
* A component to type in keywords and search for them (could be limited or general)
*  A screen to show the results, including edge cases.

## Development Complete
 The code is complete.
 Functionality is working.
 Any required downstream Docker file changes are made.
## Tests Automated
 Unit/function tests have been automated and incorporated into the build.
 100% automated unit/function test coverage for new or changed APIs.

**Comment by jouwana** [comment]
Basic UI is done, fine-tuning and connecting to a server will happen in a future sprint,
