### ISSUE TITLE
Build the web scrapper and parse the information into the database

### ISSUE THREAD

**Issue by arch-dimension** [ICST-Technion/TechnioNLPScrapper#15]
## Value Statement:
Web scrapper allows us to gather the data and save its intonation.
related to #13 - should probably work together on these issues
## Acceptance Criteria
* Successfully gathering information (title\text etc.) from multiple different websites
*  The information is parsed to a row in the database
* web scrapper connected to the database 
* Added several articles' information to the database using the web scrapper

## Development Complete
 The code is complete.
 Functionality is working.
 Any required downstream Docker file changes are made.
## Tests Automated
 Unit/function tests have been automated and incorporated into the build.
 100% automated unit/function test coverage for new or changed APIs.

**Comment by jouwana** [comment]
should we count this as complete / move it to another sprint?
