### ISSUE TITLE
fix the orientation of text in the keyword bubbles 

### ISSUE THREAD

**Issue by jouwana** [ICST-Technion/TechnioNLPScrapper#185]
the keyword bubbles are too long and the word looks like its gonna touch the top only
![image](https://github.com/ICST-Technion/TechnioNLPScrapper/assets/41836591/832c6a81-31d0-4eba-b7df-a8fc25a26d57)

or on a bigger screen:
![image](https://github.com/ICST-Technion/TechnioNLPScrapper/assets/41836591/cf47dee5-deee-4297-8011-97637766b4dd)

see if this can simply be fixed by going to CSS to '.selected-value' and changing height from 3.5vh to 2.5vh, or have it be auto height - which can be done by deleting the height setting from the CSS (this might be the better option)

make sure to check that its okay on a smaller screen as well

**Comment by layan10** [comment]
#191
