### ISSUE TITLE
Display an example graph in the UI

### ISSUE THREAD

**Issue by arch-dimension** [ICST-Technion/TechnioNLPScrapper#19]
## Value Statement:
As part of the MVP, we need to integrate the graphs and the website components
This is typically done by saving an image of the graph and embedding it in the html page.
However if the graph needs to be interactive, further research is needed.
related to #17 
## Acceptance Criteria
* Graph is showing correctly in the #14 component
## Development Complete
 The code is complete.
 Functionality is working.
 Any required downstream Docker file changes are made.
## Tests Automated
 Unit/function tests have been automated and incorporated into the build.
 100% automated unit/function test coverage for new or changed APIs.

**Comment by jouwana** [comment]
Showed 3 example graphs in the MVP UI
