### ISSUE TITLE
Intonation Evaluation Service

### ISSUE THREAD

**Issue by vMaroon** [ICST-Technion/TechnioNLPScrapper#2]
## Value Statement

For our project, we need a service to evaluate intonation of Hebrew/Arabic text.  For the MVP and per the client's requirements, a simple "keywords search" will suffice, but a smarter NLP service is preferred.

## Acceptance Criteria

A working service that receives text as input and outputs intonation quality.

### Development Complete

* [ ] Code is complete.
* [ ] Functionality is working.
* [ ] Any required downstream Docker file changes are made.

### Tests Automated

* [ ] Unit/function tests have been automated and incorporated into build.
* [ ] 100% automated unit/function test coverage for new or changed APIs.

**Comment by arch-dimension** [comment]
Currently using NLP service of IBM Watson, because it can analyze Hebrew text without translating
