### ISSUE TITLE
Solve the right to left language not showing up correctly

### ISSUE THREAD

**Issue by arch-dimension** [ICST-Technion/TechnioNLPScrapper#21]
## Value Statement:
After testing Seaborn with Hebrew, 
it appears using right-to-left languages requires a different encoding, and 
shows up in reverse on the graph, despite showing up correctly in the csv
one solution is to reverse the words, however, a way to send strings normally is preferable.
related to #17 
## Acceptance Criteria
* Hebrew titles and keywords showing up correctly in the graphs\
OR
* Working with the English version of the websites (such as YnetNews)
## Development Complete
 The code is complete.
 Functionality is working.
 Any required downstream Docker file changes are made.
## Tests Automated
 Unit/function tests have been automated and incorporated into the build.
 100% automated unit/function test coverage for new or changed APIs.

**Comment by layan10** [comment]
this will be done in frontend

**Comment by jouwana** [comment]
issue solved by using a different type of graph in frontend that supports RTL
