### ISSUE TITLE
Create responsive charts based on analysis data

### ISSUE THREAD

**Issue by layan10** [ICST-Technion/TechnioNLPScrapper#45]
using the data, use https://www.npmjs.com/package/react-chartjs-2
[chart example](https://react-chartjs-2.js.org/examples) to make built-in responsive charts, or possible other libraries if we cant find the chart design we want - though they may not all be responsive. Another library is https://react-charts.tanstack.com/

**Comment by jouwana** [comment]
added single preliminary chart
