### ISSUE TITLE
Test the API 

### ISSUE THREAD

**Issue by RazanDally** [ICST-Technion/TechnioNLPScrapper#46]
## Value Statement:
VSCode extension “thunderclient” can help to easily send and see the results of requests to APIs 
or HTTP client (in pycharm). Use them for testing
related to #43 
## Acceptance Criteria
* learn how to use these extensions
* successfully test the API
## Development Complete
 The code is complete.
 Functionality is working.
 Any required downstream Docker file changes are made.
## Tests Automated
 Unit/function tests have been automated and incorporated into the build.
 100% automated unit/function test coverage for new or changed APIs.

**Comment by arch-dimension** [comment]
used thunderclient successfully and exported the tests for future use
