### ISSUE TITLE
Turn Python into an API

### ISSUE THREAD

**Issue by RazanDally** [ICST-Technion/TechnioNLPScrapper#49]
## Value Statement:
To use python in react we need to turn it into an API
related to #46 
## Acceptance Criteria
* research Flask
* run our python program on our react website successfully.
## Development Complete
 The code is complete.
 Functionality is working.
 Any required downstream Docker file changes are made.
## Tests Automated
 Unit/function tests have been automated and incorporated into the build.
 100% automated unit/function test coverage for new or changed APIs.

**Comment by arch-dimension** [comment]
API receives requests successfully according to #46 , once the Google searching functionality is added, we can scrap the links we get as a result and insert them into the database for future use.
